### ISSUE TITLE
Allow for function to be passed in place of static key

### ISSUE THREAD

**Issue by patrickmichalina** [mcollina/fastify-secure-session#27]
I would like to rotate keys and the easiest way for an implementation like that would be to support passing in an overloaded parameter of type 'function' in order to get the keys we want used at runtime. Would you accept an PR for something like this?

**Comment by mcollina** [comment]
sure thing!

**Comment by wolfejw86** [comment]
As a point of note, with something like `express-session` an array of keys is used instead of a function.  What advantage does providing a function to get the key you want at runtime provide instead of just specifying an array of keys to the `key` option like other implementations? 
Are you wanting to rotate the key during runtime (therefore disabling all sessions created before that point in time?) or instead something like setting another cookie to track which key that user's session was signed with - ie:

```
const keys = {
  0: Buffer.from('my-random-key')
}
// /api/login
// set-cookie sessionName=mySessionCookie, keyIndex=0
// ...some time passes, key is rotated, app is redeployed (or key rotation is added dynamically during runtime, either would work i think

const keys = {
  0: Buffer.from('my-random-key'),
  1: Buffer.from('my-new-shiny-key')
}

function getKey(keyIndex) { return keys[keyIndex] }

fastify.register('fastify-secure-session', { key: getKey } );

// older session user comes back
// fastify secure-session uses `getKey(request.cookies['keyIndex']` which returns:
// keys[0] which is the correct key and will therefore decode it
```

More work on the above is definitely needed and in is likely not even a good idea, I'm just trying to gauge how you're trying to go about using a function for key rotation, partially out of curiosity, partially because I think it would be fun to implement :)

**Comment by patrickmichalina** [comment]
@wolfejw86 You could totally **not** use a function but I've found them to be the most extendable approach for future proofing these types of libraries :)

Basically just support key changes at runtime. `Buffer.from()` will be run once and not updated. I think your example updates the dictionary over time? Mutates it right? Instead I would have a service that fetches a key at runtime (ENV variables or external service doesn't technically matter).

I am using this service `https://devcenter.heroku.com/articles/securekey`.

**Comment by wolfejw86** [comment]
I figured it was some type of secret management like that. My point I’m making with the above is that from where I’m sitting a function doesn’t make it _that_ extendible because I don’t see how you keep from logging out old sessions that aren’t expired yet

**Comment by patrickmichalina** [comment]
@wolfejw86 the primary issue I want to resolve here is simply to be able to use **BOTH** the old and new keys when checking hashes.

Example: We are signing all new sessions using the newer `KEY2`. However since there are still users who have session signed against `KEY1`, we should check both during hash session validation so they can keep their session. `SECURE_KEYS=KEY1` fails so lets check against the newer `KEY2` as well (or vice versa order). Ah! that works, user is signed in with one of our rotated keys.

I think this library only allows the key to be set during initialization unless I am mistaken?


My initial thinking was to make this region more dynamic: 
```ts
if (!sodium.crypto_secretbox_open_easy(msg, cipher, nonce, key)) {
  // unable to decrypt
  request.session = new Session({})
  next()
  return
}
```

I suppose that may prove to be a little awkward thought now that I look more into it.

I think approach you mentioned will work great as long as both forms can be supported:

```ts
const keys = {
  0: Buffer.from('my-random-key'),
  1: Buffer.from('my-new-shiny-key')
}

const keys = {
  0: process.env.SECRET1
  1: () => myservice.getDynamicKey()
  2: myservice.getDynamicKey
}

```

Supporting function invocation solves the issue of changing values and there is no penalty to add simple check like `typeof key === 'function' ? key() : key`

**Comment by wolfejw86** [comment]
Hmm, I am not a fan of that approach. That puts a lot more work on the "caller" to implement. When the end goal / result is to support dynamic key rotation, this is a lot to prescribe in my opinion.  In scenario 1 of your above example the library will have to pass something back to the application to know which key to retrieve which is undesirable in my opinion.  In scenario 2, it's just a lot of overhead period as now we're back to the array style implementation due to the need to iterate over the hash somehow and also check if each one is a function or not.

I really feel like there's just an easier answer that meets the objective (key rotation and support older keys) and puts way less work on the "caller" (your application) in this scenario.

Have key be an array (in your heroku example parsed from a comma-separated value env variable) and just pass that in (`Array<string | Buffer>`)

I took a stab at implementing it here - https://github.com/mcollina/fastify-secure-session/pull/28

**Comment by patrickmichalina** [comment]
How is it more work?

```ts
type Key = string | () => string
```

**Comment by wolfejw86** [comment]
> How is it more work?

I may just be operating on a different wavelength here or something. I get that it's complicated to support a function to get a key, I guess I read your initial issue question that has the main objective of rotating keys.  

Reading it again, it seems like from your perspective you're more interested in a key that is simply represented as a function that returns the value for the key.  I get that that _by itself_ is very simple, but I actually see it as a completely separate thing from key rotation.  I'll remove the reference to this issue with my PR and keep its scope _just_ to key rotation.  

I don't have a use case for a key being represented by a function, I care a lot more about being able to rotate keys in a way that doesn't log people out.  Sorry for any confusion

**Comment by patrickmichalina** [comment]
@wolfejw86 gotcha. Thanks yeah I guess there are two topics here and I casually blended both together. I think your implementation works, I only worry that it doesn't solve the _generic_ case of those values changing up under you at runtime (which may never happen in many cases).

**Comment by wolfejw86** [comment]
Yeah you're right. I want to think about it some more. Even though that's not a situation I'm used to, it's probably worth supporting 🤔
